config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :proponents
  root 'proponents#index'

  get 'inss/calculation'
  get 'relatory/index'
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id           :bigint           not null, primary key
#  cep          :string
#  city         :string
#  neighborhood :string
#  number       :string
#  state        :string
#  street       :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Address < ApplicationRecord
  has_one :proponent

  validates :cep, presence: true
  validates :city, presence: true
  validates :neighborhood, presence: true
  validates :number, presence: true
  validates :state, presence: true
  validates :street, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inss.rb
# == Schema Information
#
# Table name: insses
#
#  id         :bigint           not null, primary key
#  aliquot    :float            not null
#  from       :float            not null
#  to         :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Inss < ApplicationRecord
  validates :aliquot, presence: true
  validates :from, presence: true
  validates :to, presence: true
end

app/models/phone.rb
# == Schema Information
#
# Table name: phones
#
#  id           :bigint           not null, primary key
#  number       :string
#  reference    :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  proponent_id :bigint           not null
#
# Indexes
#
#  index_phones_on_proponent_id  (proponent_id)
#
# Foreign Keys
#
#  fk_rails_...  (proponent_id => proponents.id)
#
class Phone < ApplicationRecord
  belongs_to :proponent

  validates :number, presence: true
end

app/models/proponent.rb
# == Schema Information
#
# Table name: proponents
#
#  id                 :bigint           not null, primary key
#  birth_date         :date
#  cpf                :string
#  inss_aliquot       :float
#  inss_dedution      :float
#  inss_liquid_salary :float
#  name               :string
#  salary             :decimal(8, 2)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  address_id         :bigint           not null
#
# Indexes
#
#  index_proponents_on_address_id  (address_id)
#
# Foreign Keys
#
#  fk_rails_...  (address_id => addresses.id)
#
require 'cpf_cnpj'

class Proponent < ApplicationRecord
  paginates_per 5

  belongs_to :address
  has_many :phone

  accepts_nested_attributes_for :phone, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true

  validates :cpf, presence: true
  validates :name, presence: true
  validates :salary, presence: true

  validate :valid_cpf?
 
  after_create :create_salary_dependeces

  def valid_cpf?
    errors.add('CPF não e valido') unless CPF.valid?(self.cpf) 
  end

  def create_salary_dependeces
    CreateSalaryDependecesWorker.perform_async(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  before_action :set_proponent, only: %i[ show edit update destroy ]

  # GET /proponents or /proponents.json
  def index
    @proponents = Proponent.order(:created_at).page(paginate_params[:page]).per(paginate_params[:per_page])
  end

  # GET /proponents/1 or /proponents/1.json
  def show
  end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
    @proponent.build_address
    @proponent.phone.build
  end

  # GET /proponents/1/edit
  def edit
  end

  # POST /proponents or /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)

    if @proponent.save
        redirect_to proponent_url(@proponent), notice: 'Proponent was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /proponents/1 or /proponents/1.json
  def update
    respond_to do |format|
      if @proponent.update(proponent_params)
        format.html { redirect_to proponent_url(@proponent), notice: 'Proponent was successfully updated.' }
        format.json { render :show, status: :ok, location: @proponent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proponents/1 or /proponents/1.json
  def destroy
    @proponent.phone.destroy_all
    @proponent.destroy

    respond_to do |format|
      format.html { redirect_to proponents_url, notice: 'Proponent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proponent
      @proponent = Proponent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proponent_params
      params.require(:proponent).permit(
        :name,
        :cpf,
        :address_id,
        :birth_date,
        :salary,
        address_attributes: [
          :cep,
          :city,
          :neighborhood,
          :number,
          :state,
          :street
        ],
        phone_attributes: [
          :id,
          :number,
          :reference,
          :_destroy
        ])
    end

    def paginate_params
      params.permit(
        :page, :per_page
      )
    end
end

app/controllers/relatory_controller.rb
class RelatoryController < ApplicationController
  def index
    aliquot = Inss.order(:aliquot).pluck(:aliquot)
    @data_keys = Inss.order(:aliquot).pluck(:from, :to)
    proponent = Proponent.group(:inss_aliquot).count
    @data_values = aliquot.collect{|d| proponent[d]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/helpers/relatory_helper.rb
module RelatoryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticCode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proponents/_address_fields.html.erb
<div class="mb-3">
  <%= form.label :cep, class: "form-label" %>
  <%= form.text_field :cep, class: "form-control"%>
</div>

<div class="mb-3">
  <%= form.label :city, class: "form-label" %>
  <%= form.text_field :city, class: "form-control"%>
</div>

<div class="mb-3">
  <%= form.label :neighborhood, class: "form-label" %>
  <%= form.text_field :neighborhood, class: "form-control"%>
</div>

<div class="mb-3">
  <%= form.label :number, class: "form-label" %>
  <%= form.text_field :number, class: "form-control"%>
</div>

<div class="mb-3">
  <%= form.label :state, class: "form-label" %>
  <%= form.text_field :state, class: "form-control"%>
</div>

<div class="mb-3">
  <%= form.label :street, class: "form-label" %>
  <%= form.text_field :street, class: "form-control"%>
</div>

app/views/proponents/_form.html.erb
  <%= form_with(model: proponent) do |form| %>
<div class="row justify-content-md-center">
    <div class="col col-md-6">
      <div class="card-custom mb-3">
        <div class="card-header">
          <h2>Proponent</h2>
        </div>
        <div class="card-body">
          <% if proponent.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(proponent.errors.count, "error") %> prohibited this proponent from being saved:</h2>

              <ul>
                <% proponent.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :name, class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :cpf, class: "form-label" %>
            <%= form.text_field :cpf, class: "form-control"%>
          </div>

          <div class="mb-3">
            <%= form.label :birth_date, class: "form-label" %>
            <%= form.date_field :birth_date, class: "form-control"%>
          </div class="mb-3">

          <div class="mb-3">
            <%= form.label :salary, class: "form-label" %>
            <%= form.text_field :salary, class: "form-control"%>
          </div>

            <%= form.fields_for :phone do |form| %>
            <%= render "phone_fields", :form => form %>
          <% end %>
          <%= link_to_add_nested(form, :phone, '#phone', link_classes: 'btn btn-primary') %>
        </div>
      </div>
    </div>

    <div class="col col-md-6">
      <div class="card-custom mb-3">
        <div class="card-header">
          <h2>Address</h2>
        </div>
        <div class="card-body">
          <%= form.fields_for :address_attributes do |form| %>
            <%= render "address_fields", :form => form %>
          <% end %>
        </div>
      </div>
    </div>

   
     

       

    <div class="mb-3">
      <%= form.submit class: "btn btn-primary"%>
    </div>
</div>
  <% end %>

app/views/proponents/_phone_fields.html.erb
<div class="card-custom mb-3 mt-5"  id='phone'>
  <div class="card-header">
    <h2>Phone</h2>
  </div>
   <div class="card-body">
    <div class="mb-3">
      <%= link_to_remove_nested(form, link_classes: 'btn btn-danger error_nexted') %>
    </div>
    <div class="mb-3">
      <%= form.label :number, class: "form-label" %>
      <%= form.text_field :number, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= form.label :reference, class: "form-label" %>
      <%= form.text_field :reference, class: "form-control"%>
    </div>
  </div>
</div>

app/views/proponents/_proponent.html.erb
<div class="row">
  <div class="col-m12">
    <div id="<%= dom_id proponent %>">
    
      <p>
        <strong>Name:</strong>
        <%= proponent.name %>
      </p>

      <p>
        <strong>Cpf:</strong>
        <%= proponent.cpf %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= proponent.address.street %>
      </p>

      <p>
        <strong>Birth date:</strong>
        // <%= proponent.birth_date.strftime("%d/%m/%Y") %>
      </p>
       <p>
        <strong>Salary:</strong>
        <%= number_to_currency(proponent.salary) %>
      </p>
      <p>
        <strong>Inss Dedution:</strong>
        <%= number_to_currency(proponent.inss_dedution) %>
      </p>
      <p>
        <strong>Inss aliquot:</strong>
        <%= number_to_percentage(proponent.inss_aliquot, precision: 1) %>
      </p>
      <p>
        <strong>Inss Liquid Salary :</strong>
        <%= number_to_currency(proponent.inss_liquid_salary) %>
      </p>
      
    </div>
  </div>
</div>

app/views/proponents/edit.html.erb
<div class="container">
  <h1>Editing proponent</h1>
  <%= render "form", proponent: @proponent %>

  <div>
    <%= link_to "Show this proponent", @proponent %> |
    <%= link_to "Back to proponents", proponents_path %>
  </div>
</div>

app/views/proponents/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <%= link_to "Back to relatory", relatory_index_path %>

  <h1>Proponents</h1>

  <div id="proponents">
     <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Birth Date</th>
          <th scope="col">Cpf</th>
          <th scope="col">Salary</th>
          <th scope="col" colspan="2">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @proponents.each do |proponent| %>
        <tr>
          <td scope="row"><%= proponent.id %></td>
          <td><%= proponent.name %></td>
          <td><%= proponent.birth_date.strftime("%d/%m/%Y") %></td>
          <td><%= proponent.cpf %></td>
          <td><%= number_to_currency(proponent.salary) %></td>
          <td> <%= link_to "Show", proponent %></td>
          <td> <%= link_to "Destroy", proponent_path(proponent), method: :delete %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
    <%= paginate @proponents, class: "d-flex"%>
  </div>

  <%= link_to "New proponent", new_proponent_path, class: "btn btn-primary" %>
</div>

app/views/proponents/new.html.erb
<div class="container">
  <h1>New proponent</h1>
  <%= link_to "Back to proponents", proponents_path %>
  <%= render "form", proponent: @proponent %>
</div>

app/views/proponents/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="row justify-content-md-center">
    <div class="col col-md-6">
      <div class="card-custom mb-3">
        <div class="card-header">
          <h2>Proponent</h2>
        </div>
        <div class="card-body">
          <%= render @proponent %>

          <%= link_to "Edit this proponent", edit_proponent_path(@proponent) %> 
          <%= link_to "Back to proponents", proponents_path %>
          <%= button_to "Destroy this proponent", @proponent, method: :delete %>
        <div>
      </div>
    </div> 
  </div> 
</div> 

app/views/relatory/index.html.erb
<div class="container">
  <%= link_to "Back to proponents", proponents_path %>

  <h1>Relatory</h1>

  <canvas id="myChart" width="200px" height="100px" ></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
const ctx = document.getElementById('myChart');

new Chart(ctx, {
  type: 'bar',
  data: {
	labels: <%= @data_keys.to_json.html_safe %>,
	datasets: [{
	  label: '# aliquota per salary',
	  data: <%= @data_values.to_json.html_safe %>,
	  borderWidth: 1
	}]
  },
  options: {
	scales: {
	  y: {
		beginAtZero: true
	  }
	}
  }
});
</script>